### PR TITLE
Updated index.html with the freshest, organically sourced JavaScript frameworks.

### PR DESCRIPTION
**Pull request by AnonGuy**

### CODE REVIEW

**Comment by Dex56811** [comment]
_some_

**Comment by AnonGuy** [comment]
Yeah, I understand. We need a lot more than this.

**Comment by david-cooke** [comment]
I can see how much this will enhance the website already. More need adding though.

**Comment by AnonGuy** [comment]
I'll get to work adding some of the fastest frameworks I can find.

**Comment by Dex56811** [comment]
lmao this website is going to be so fucking scuffed

**Comment by david-cooke** [comment]
*beautiful

**Comment by david-cooke** [comment]
Have you considered adding css frameworks?

**Pull request merged**
